all: xwinp xwinp1 xwinp2 xwinp3 xwinp4

xwinp: xwinp.c
	gcc xwinp.c -Wall -oxwinp -lX11 -lpthread

xwinp1: xwinp1.c
	gcc xwinp1.c -Wall -oxwinp1 -lX11 -lpthread

xwinp2: xwinp2.c
	gcc xwinp2.c -Wall -oxwinp2 -lX11 -lpthread

xwinp3: xwinp3.c
	gcc xwinp3.c -Wall -oxwinp3 -lX11 -lpthread

xwinp4: xwinp4.c
	gcc xwinp4.c -Wall -oxwinp4 -lX11 -lpthread

clean:
	rm -f xwinp xwinp1 xwinp2 xwinp3 xwinp4

